### ISSUE TITLE
"Plate file" doesn't seem to exist?

### ISSUE THREAD

**Issue by samvaughan** [samvaughan/Hector-Observations-Pipeline#16]
Hi Ayoan, 

I've just tried running your allocation code on some configured fields (with ```HP.allocate_hexabundles_for_single_tile(tile_number=0)``` and I get the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'Outputs/Clusters/Cluster1/Allocation/Hexa_and_Guides_Cluster_1_tile_000.txt'
```

Line 375 in `pipeline.py` sets up the filename of the `plate_file`:

```python
plate_file = f"{self.allocation_files_location_base}/Hexa_and_Guides_{self.config['output_filename_stem']}_tile_{tile_number:03d}.txt"
```
And then it gets used in line 378: 

```python
#### Offset function: thermal coefficient based movement of magnet pair as a whole
plate_file,magnetPair_offset = offsets.magnetPair_radialPositionOffset(plate_file)
```

Next, ```offsets.magnetPair_radialPositionOffset(plate_file)``` tries to read in this plate file in line 76:

```python
csv_input = pd.read_csv(plate_file)
```

and that's where the error comes from- it doesn't exist yet! I thought that this plate file was made by your code- is that not correct?

I'm not sure how I didn't run into this issue before, when I got  ``````HP.allocate_hexabundles_for_single_tile()``` to work... But yeah, do you know what's happening here? Thanks!

**Comment by asad9520** [comment]
Hi Sam, sorry was making some changes just a while back and one function was being called before the plate_file got created. It should be fixed now.

**Comment by samvaughan** [comment]
Awesome, thanks!
