### ISSUE TITLE
To produce plot showing changes in skyfibres since last field 

### ISSUE THREAD

**Issue by asad9520** [samvaughan/Hector-Observations-Pipeline#18]
Please uncomment these set of lines when u want to run plot that shows which sky fibres have changed since the last field plugged.

https://github.com/samvaughan/Hector-Observations-Pipeline/blob/71e9eff321032c7f9adcbac42c1de8ea907ba5cd/hop/pipeline.py#L599

**Comment by samvaughan** [comment]
Awesome, thanks!
