### ISSUE TITLE
Typo in file output?

### ISSUE THREAD

**Issue by samvaughan** [samvaughan/Hector-Observations-Pipeline#19]
Hi @asad9520, 

I think that there's a typo in the column names in the tile file output  (e.g. `tile_GAMA_G15_tile_000.txt`.)

The column name should be (I think!)  `'rectMag_inputOrientation'` but in the actual output file it's being written as `rectMag_inputOrienta`. I can't understand why this is the case though... The column name is correct in `pipeline.py` (lines 550 and 551) so I can't see why the last few letters are being cut off. Do you have any ideas?

Thanks!
Sam

**Comment by asad9520** [comment]
Hi @samvaughan, this has been solved. It was due to numpy array data type being used having a limitation of some sort. I have changed the data type to recommended type that resolves this problem.
