### ISSUE TITLE
Have one source for the "allocate_hexas" function

### ISSUE THREAD

**Issue by samvaughan** [samvaughan/Hector-Observations-Pipeline#3]
Currently it's a method to the HectorPipeline class as well as a function in ```hop/hexabundle_allocation/allocate_hexabundles.py``` and ```hop/hexabundle_allocation/AyoanPC_main_hexabundleAllocation.py``` with copied and pasted code. 

Ideally I think it should remain a method to the class and we'll delete the ```allocate_hexabundles.py``` and ```AyoanPC_main_hexabundleAllocation.py``` files. But we'll have to allow the user to __just__ run the allocation and specify the correct file paths for everything

**Comment by samvaughan** [comment]
Hi @asad9520, 

I noticed your ```hop/hexabundle_allocation/AyoanPC_main_hexabundleAllocation.py``` file, and what you needed to do for all the paths and locations in order to get it running on your PC. Can you test out something for me? I've written a configuration file which should have the file locations for your PC in (it's going to look for files in ```D:/Hector/Hector_project_files/Hector/magnet_position/For_Ayoan_14p5_exclusion_Clusters/Cluster_2```). I've then made the simple example script ```Ayoan_example_script.py```, which loads in this configuration file and runs the hexabundle allocation code on just tile number 0 in that folder. 

Can you pull the latest version of the repo and see if this works for you? E.g. just try running ```Ayoan_example_script.py``` on your machine. If it doesn't work, let me know what errors you get? 

Hopefully this will mean that we can delete the ```AyoanPC_main_hexabundleAllocation.py``` and ```allocate_hexabundles.py ``` files in ```hop/hexabundle_allocation/```, and just use the ```allocate_hexabundles_for_single_tile``` method of the HectorPipeline class ([194-284 of pipeline.py](https://github.com/samvaughan/Hector-Observations-Pipeline/blob/33f38fd328fe7d0894bc537cc37b8fbdf1a846b7/hop/pipeline.py#L194)). 

This will also mean that any updates you make to this file are only in one place- rather than you updating one file and me accidentally using another/old version of it. Thanks!

**Comment by samvaughan** [comment]
I just made a quick update to the example config files (here: 9c8598a46da6706bea284a65a310b30a47b55115) to fix a bug

**Comment by asad9520** [comment]
Hi Sam, I am getting the following error when trying to run File **Ayoan_example_script.py** 
```
"E:\Gitlab\Hector-Observations-Pipeline\hop\misc\misc_tools.py", line 5, in <module>
    import pandas_tools as P 
ModuleNotFoundError: No module named 'pandas_tools'
```
I do have the pandastools package installed. Is there any other pandas package other than pandas and pandastools that is required to be installed

**Comment by samvaughan** [comment]
Whoops, no that's my bad. Hang on, I'll add the correct path to that

**Comment by samvaughan** [comment]
Okay I've updated that import. Can you try again?

**Comment by asad9520** [comment]
Hi Sam, the code is working fine on my computer as well. Thanks

**Comment by samvaughan** [comment]
Awesome, great. So are you happy to make any changes to the```allocate_hexabundles_for_single_tile``` method in ```pipeline.py``` rather than editing the other files we have? Just so that we're both working on the same things

**Comment by asad9520** [comment]
Yeah, absolutely. Make it more convenient for us both. Thanks

**Comment by samvaughan** [comment]
Awesome, I'll close this then
