### ISSUE TITLE
A new error in pipeline.py 

### ISSUE THREAD

**Issue by asad9520** [samvaughan/Hector-Observations-Pipeline#9]
https://github.com/samvaughan/Hector-Observations-Pipeline/blob/96ed088365672a082a60c7757af24319caf3f781/hop/pipeline.py#L69

Hi Sam, I am getting the following error, not sure what's the source:

`Traceback (most recent call last):
  File "E:/Gitlab/Hector-Observations-Pipeline/Ayoan_example_script.py", line 10, in <module>
    HP = pipeline.HectorPipe(config_filename="ConfigFiles/Ayoan_example_config_Cluster2.yaml")
  File "E:\Gitlab\Hector-Observations-Pipeline\hop\pipeline.py", line 69, in __init__
    raise NameError("The Distortion Correction binary seems to not exist")
NameError: The Distortion Correction binary seems to not exist`

**Comment by samvaughan** [comment]
Hi Ayoan,

My bad, I'd forgotten that you didn't have that file. I've added it to the repo and so if pull the latest version then that error should go away!

**Comment by asad9520** [comment]
Thanks Sam. Works fine now.
